### ISSUE TITLE
Multi-Core System Monitor doesnt show swap usage

### ISSUE THREAD

**Issue by renarena** [linuxmint/cinnamon-spices-applets#5177]
### Applet version/Build date

1.9.4 (2023-10-29 17:22:51)

### Cinnamon version

5.8.4

### Distribution

LMDE6

### Graphics hardware *and* driver used

GeForce GTX 1050, NVRM version: NVIDIA UNIX x86_64 Kernel Module  525.125.06, GCC version:  gcc version 12.2.0 (Debian 12.2.0-14) 

### Applet name and maintainer

multicore-sys-monitor@ccadeptic23 @claudiux

### What happened?

Applet doesnt show used swap. The bar behind the circle is always empty.
There is a single dot(?) bottom left in blue swap color.

### Other information

Probably this also occurred on LMDE5, i do not remember the last time i see swap usage.

**Comment by claudiux** [comment]
Ah. I have a problem with nvme disks. I'll try to fix it.

**Comment by jjadup** [comment]
@claudiux my system (also nvme) doesn't show the swap usage, and `swapon --show` for me yields
```
/swapfile file   2G 428.1M   -2
```
More annoyingly though, my entire memory graphic keeps disappearing, usually when my memory usage gets high.

**Comment by renarena** [comment]
Any change this will be fixed?
My machine lastly started again to not resume from hibernation (rather then not going to sleep), probably because of too much used swap, so i really would like to see my swap usage.

**Comment by claudiux** [comment]
This applet uses GTop, which does not correctly read data from nvme disks.

Instead of GTop, I'll use the return of this command: `swapon --show=SIZE,USED | tail +2`.

On my computer, it returns:
`30,5G 768K`

My goal is to stop using GTop.

**Comment by claudiux** [comment]
Fixed! I'll do a PR soon.

**Comment by claudiux** [comment]
Done! I hope you'll like it.

**Comment by renarena** [comment]
I anyhow missed this. But i still do not see any swap usage (should be red) in the memory icon in V1.9.9 (2025-06-15 17:45:47)
![Image](https://github.com/user-attachments/assets/03080f74-6c17-42b2-b81f-14771305abd3)

**Comment by claudiux** [comment]
Please try increasing the size of memory box in settings.

**Comment by renarena** [comment]
if i do so, a small line on left appears. in the past the entire background behind the circle was filled with the selected color.

**Comment by claudiux** [comment]
Ok, I'll try to add an option to select the width of this bar.

**Comment by renarena** [comment]
i just updated the app. Now its like it used to be, background shows swap usage - thank you very much!!!
