### ISSUE TITLE
feeds@jonbrettdev.wordpress.com don't work

### ISSUE THREAD

**Issue by muzena** [linuxmint/cinnamon-spices-applets#526]
@jake1164
Feeds aplet don't work.
I think, the path in line 30 or 31 applet.js file is incorrect.
when i changed line 30
const DATA_PATH = GLib.get_home_dir() + "/.cinnamon/" + UUID;
to
const DATA_PATH = GLib.get_home_dir() + "/.cinnamon/configs/" + UUID;
then applet work.
Also applet won't remember manually add feeds, after restarting PC they dissapear.
Left click on applet -> Configure... also don't work.

**Comment by jake1164** [comment]
@muzena let me know if the updates resolve your issues.

**Comment by jake1164** [comment]
@NikoKrause @collinss This has been resolved in my testing.

**Comment by muzena** [comment]
@jake1164 
I still have this problem?

 Left click on applet -> Configure... also don't work.

**Comment by jake1164** [comment]
What version of Linux?
Right click on the app and select About. What version of the applet does it display?

**Comment by collinss** [comment]
The configure problem was resolved in Cinnamon yesterday by https://github.com/linuxmint/Cinnamon/pull/6518.

**Comment by jake1164** [comment]
@muzena You can get configure working by deleting the feeds.json file in ~/.cinnamon/configs/feeds@jonbrettdev.wordpress.com/

**Comment by muzena** [comment]
It works now with @collinss patch.
