### ISSUE TITLE
Radio3.0: pipewire-pulse shouldn't be installed on pulseaudio systems

### ISSUE THREAD

**Issue by dtl131** [linuxmint/cinnamon-spices-applets#6583]
### Applet version/Build date

git

### Cinnamon version

Irrelevant

### Distribution

Mint 21.x

### Graphics hardware *and* driver used

Irrelevant

### Applet name and maintainer

Radio3.0@claudiux @claudiux

### What happened?

https://github.com/linuxmint/cinnamon-spices-applets/pull/6558
^This pull installs pipewire-pulse package on Mint 21.x, which breaks audio for users until pipewire-pulse is removed: https://forums.linuxmint.com/viewtopic.php?t=434287

Mint 21 uses pipewire for video, but uses pulseaudio for sound.

**Comment by claudiux** [comment]
Thanx for reporting this issue. I'll fix it soon.

**Comment by claudiux** [comment]
Done!

**Comment by dtl131** [comment]
> Done!

Hmm. You may still encounter corner cases where people reverted to using Pulseaudio in Mint22 (but still have Pipewire installed for video). It's a lot better than it was though. Thanks for quick response.

**Comment by claudiux** [comment]
> 
> Hmm. You may still encounter corner cases where people reverted to using Pulseaudio in Mint22 (but still have Pipewire installed for video). It's a lot better than it was though. Thanks for quick response.

Hmm. In addition, you may come across special cases where people (like me) have installed Pipewire in Mint 21.3: https://github.com/orgs/linuxmint/discussions/462
