### ISSUE TITLE
sound150@claudiux pops up the speaker icon when cinnamon is restarted

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-applets#6728]
### Applet version/Build date

Version 7.4.0 (2024-12-30 15:54:14)

### Cinnamon version

Cinnamon 6.2.9

### Distribution

Linux Mint 22 x86_64

### Graphics hardware *and* driver used

Intel UHD Graphics 620

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

I think this is a regression.  Every time I do a restart of cinnamon or change themes, the volume icon and slider appear for a few seconds.

**Comment by claudiux** [comment]
Fixed in #6730.

**Comment by ChooChooAl** [comment]
Just installed latest, restart cinnamon, it's there still.
Version 7.4.1 (2025-01-03 11:53:34)d
![image](https://github.com/user-attachments/assets/3424c733-4618-441e-b3cc-5c67a1c630b2)

**Comment by ChooChooAl** [comment]
Version 7.4.1 (2025-01-03 15:40:41) still does it.

**Comment by claudiux** [comment]
Ah OK, I didn't make any changes for Cinnamon 6.2, only for 6.4. I'm reopening this issue.

**Comment by claudiux** [comment]
Solved! I'll do a PR soon.

**Comment by claudiux** [comment]
Done!

**Comment by ChooChooAl** [comment]
Uh, hate to say this but... Version 7.4.2 (2025-01-03 19:39:27) still not working.   I'm headed to bed.

**Comment by claudiux** [comment]
@ChooChooAl 
Please check in the applet settings that this box is not checked:

![image](https://github.com/user-attachments/assets/ae71f93e-0587-4291-b4bb-959a80efd787)

**Comment by claudiux** [comment]
Oh, I see. I reopen this issue.

**Comment by ChooChooAl** [comment]
It's turned off.   Is it of any concern that my config isn't the same as yours?
![image](https://github.com/user-attachments/assets/c8bc1a3b-1883-4f5d-8245-1ca6bd7ca52a)

**Comment by claudiux** [comment]
This is correct. I've found the bug. I'll do a new PR soon.

**Comment by claudiux** [comment]
Done!

**Comment by ChooChooAl** [comment]
Yes.  Thank you.
