### ISSUE TITLE
multicore-sys-monitor:  CPU Usage does not seem to be accurate.

### ISSUE THREAD

**Issue by Tater-K7S5A** [linuxmint/cinnamon-spices-applets#7445]
### Applet version/Build date

2.1.0

### Cinnamon version

6.4.8

### Distribution

Mint 22.1 Cinnamon

### Graphics hardware *and* driver used

AMD Radeon RX580 GTS AMDGPU

### Applet name and maintainer

multicore-sys-monitor@ccadeptic23 @claudiux

### What happened?

Thank you for your hard work!  I really appreciate how much you do for us Claudiux.

I upgraded this morning to 2.0.0 and noticed that the CPU display is showing about 50% usage on all cores.  But that is not the actual situation.  Looking at System Monitor it shows the cores idling.  My CPU temp (49c) likewise is indicative of my system not doing much.

Here is an image of the applet and System Monitor having a disagreement. 

<img width="2239" height="1645" alt="Image" src="https://github.com/user-attachments/assets/42f3551d-19d7-48ce-9476-8d8472f3fe8c" />

**Comment by tuxfanmatze** [comment]
I have the same issue.

**Comment by Bernsteinnn** [comment]
Just to confirm that I’m also still experiencing this issue with v 2.1.0 on Mint 22.1 Cinnamon 6.4.8, running an AMD Radeon RX 7800 XT (AMDGPU driver).

I previously commented in issue #7440 and linked to #7439 to note that 2.1.0 didn’t resolve the regressions introduced in 2.0.0 for me. Since then, I’ve removed the applet, deleted its local directory and config, then re-downloaded and reconfigured it via the Applets interface. That did fix the broken click behavior (#7439) on my system.

However, the CPU graphs remain entirely white when using the `Color by activity level` setting. Colors appear as expected only when switching to `Use automatic colors`. This seems to match the report in #7443, which was closed after the 2.1.0 release but appears to remain unresolved.

Thanks for continuing to improve what’s easily one of Cinnamon’s most valuable applets.

**Comment by claudiux** [comment]
Solution found for the CPUs graph. I'll update it soon.

**Comment by claudiux** [comment]
Solved in v2.2.0.

**Comment by Tater-K7S5A** [comment]
Thank you very much.  I just updated and it appears to be fixed.

**Comment by Bernsteinnn** [comment]
Thanks for another quick update!

Unfortunately, `Color by activity level` still doesn't work for me.

<img width="499" height="666" alt="Image" src="https://github.com/user-attachments/assets/5ec48ad5-7c07-4e7f-a8a7-9a43ae1c772c" />

Additionally, the CPU load displayed in the applet differs significantly from what’s shown in htop and System Monitor. It consistently displays 0%, even when a core is clearly active. Is this an intentional design choice?

<img width="1579" height="457" alt="Image" src="https://github.com/user-attachments/assets/807c7b40-8a1e-48d1-9ad4-e0707519b71b" />


As a side note, it seems that issues are being closed as soon as an update is published that is supposed to resolve them, without waiting for user feedback to confirm whether the fix worked. If that’s your preferred approach, would you like users to open a new issue when bugs persist after an update?

**Comment by Bernsteinnn** [comment]
I don't think the CPU usage is fixed; I suggest reopening this issue. The lowest actual CPU load shown in the applet seems to be 9%. Any usage below that threshold seems to be rendered as 0%.

Out of curiosity, I had a look at the latest commit. There are several //FIXME comments still present in the code, which suggests this was intended more as a quick patch to restore functionality after the regressions in 2.0, rather than a fully polished update, and it might have been helpful to express that more clearly. 
I realize that this has all been handled over the weekend and really appreciate the effort you've put into getting the applet back into usable shape so quickly. 
Still, in this context, closing all related issues immediately after each release without waiting for confirmation from users that the problems were resolved may not have been the best move in this particular case.

**Comment by claudiux** [comment]
The values displayed by this applet and those displayed by the system monitor will almost never be identical, because measurements cannot (except by extraordinary chance) be taken at exactly the same moment.

The measured values will be more accurate in version 2.2.1.

**Comment by Bernsteinnn** [comment]
That makes sense in principle, but just to clarify, I’m not expecting the applet to match htop or System Monitor exactly.

The attached screenshot was meant to illustrate just how far off the applet’s values are from other tools. 
In that example, 12 out of 16 cores showed 0% usage, even though other tools reported activity on all cores. 
Under low-load conditions, about half of my cores display either 0% or 9%, and I never see values between those two.
That’s not a timing offset.

I also wanted to flag that the `Color by activity level` feature still seems non-functional.

If 2.2.1 specifically addresses these points, that’s great, and I’m glad to hear it. I had assumed they were still unaddressed, since the issue was already closed.

**Comment by ikester8** [comment]
The fix appears to work for me, thank you!

**Comment by Bernsteinnn** [comment]
Can confirm that the issue appears to be fixed as of version 2.2.1. The widened sampling interval has resolved the 0% floor effect and seems to have made the readouts significantly more granular and accurate, especially at low CPU usage.

To illustrate the difference, here are two sets of raw readings captured via get-cpu-data3.sh, before and after the update:

2.2.0:
`12.8834 33.3333 33.3333 25 11.1111 18.1818 20 0 9.09091 22.2222 10 0 0 9.09091 0`

2.2.1:
`12.005 21.4286 17 16 14.1414 10.101 8.08081 7.92079 8.08081 19 19.7917 11.2245 8.91089 8 7.07071 7.07071 6.06061`

Thanks again for taking the time to address the bulk of the regressions introduced in v2.0.0, especially over the course of a weekend.

That said, I’d still appreciate a fix for the remaining issue with the `Color by Activity Level` feature when time allows. One of the applet’s core strengths is that it provides at-a-glance insight into system load, and being able to customize the graph colors helps make that visual feedback intuitive.

**Comment by claudiux** [comment]
Colors problem fixed in v2.3.2.
