### ISSUE TITLE
Direct@claudiux: 'FAVORITES' not translated and not renamable

### ISSUE THREAD

**Issue by C-O-D** [linuxmint/cinnamon-spices-applets#7905]
### Applet version/Build date

1.1.2

### Cinnamon version

6.4.12

### Distribution

Manjaro 25.0.10

### Graphics hardware *and* driver used

AMD Radeon 780M, amdgpu

### Applet name and maintainer

Direct@claudiux @claudiux 

### What happened?

I want to rename the word 'FAVORITES' in the main panel to FAVORITEN (since it is not translated to german) but then it resets itself to it's original name and also to it's original postion. I tried to put it into de.po but this doesn't get respected as well. Furthermore, none of the headings can be renamed, although the Edit button implies this - everything is reset again including the position.

**Comment by claudiux** [comment]
OK. I will fix this issue but `de.po` should be updated by a translator.

de: 67 messages translated, 5 approximate translations, 19 messages not translated.

**Comment by claudiux** [comment]
Done.

**Comment by C-O-D** [comment]
> Done.

Unfortunately, I have to say that the symptoms are still the same as before. Favorites is still not translated, which wouldn't be a problem if I could rename it, but as I said, that's not possible when I try to do so in the settings. What is the edit button for if the edit is not accepted?

**Comment by claudiux** [comment]
Please update this applet.

System settings -> Applets -> Download tab: sort as Upgradable -> update.

Then restart Cinnamon or logout/login.

**Comment by C-O-D** [comment]
"Favorites" has now been translated, thank you very much.
However, renaming one of the four main entries in the settings still does not work. I don't know if this is intentional, but personally it's not that important to me anymore, I just wanted to mention it...

**Comment by claudiux** [comment]
That's normal. These sections are there to be moved, not renamed.
